### ISSUE TITLE
Make more general interface

### ISSUE THREAD

**Issue by SeungheonOh** [Liqwid-Labs/plutarch-script-export#6]
Across Agora and Liqwid-onchain, script exporting is all over the place. Instead, `plutarch-script-export` should provide a common interface to 
- export scripts to different formats (RESTful API, JSON, etc)
- share a common script testing framework (`plutarch-unit`)
- allow easy importing from other projects.

Some plans:

`ScriptInfo` should be updated to include script name, script, and debug script (in `Script` type). Currently, it only contains serialized scripts in `Text` -- not ideal when testing or exporting to other formats. There should be other types for each export methods.

Need to "tag" `ScriptInfo` and specify its kind.

Questions:

Should `ScriptInfo` contain a Plutarch Type? It would make testing easier since Plutarch terms can be applied. Also, I think it can be a better version of tagging script kind. 

But if we include Plutarch Type, why not just have `Term` internally instead of `Script? We can have evaluated terms with different trace options. 

What should be included in `ScriptInfo` besides things mentioned above?

**Comment by emiflake** [comment]
> Should ScriptInfo contain a Plutarch Type?

I reckon not. We should be lawful with JSON encoding/decoding, and encoding a `Term` with Aeson isn't possible. Besides, plutus terms can also be applied!
```hs
applyArguments :: Script -> [PLC.Data] -> Script
applyArguments (Script p) args =
     let termArgs = Haskell.fmap (PLC.mkConstant ()) args
         applied t = PLC.mkIterApp () t termArgs
     in Script $ over UPLC.progTerm applied p
```
This is, after all, all that `ctl-server` does.

Taking this idea further, then, we could somehow expose only pure `Scripts` that are unapplied at the Plutus-level, as opposed to the Plutarch-level. This is complicated for Agora's current setup, but is something we can try to work around.

Doing this, would allow us to use [ply](https://github.com/mlabs-haskell/ply), which would mean we get to export things for free using their system.

Still, `plutarch-script-export` ought to be able to provide fully applied scripts too, so we would need separate endpoints for applied and unapplied scripts (unless we want to use `ctl-server` which is also an option!)

**Comment by SeungheonOh** [comment]
> I reckon not. We should be lawful with JSON encoding/decoding, and encoding a Term with Aeson isn't possible. Besides, plutus terms can also be applied!

We will need another type for this specific purpose. I was talking in test-writing point of view since using `applyArguments` can be quite frustrating unless you are using `Validator` or `Policy`. I thought having Plutarch type would help in this situation. F

However, I think we would rarely encounter exporting script besides `Validator` or `Policy`, so I think `Script` would be fine. Also, it seems like Ply only supports `Validator` or `Policy`.

Regarding Ply, which I'm not very familiar with, I think we can use [TypedScript](https://github.com/mlabs-haskell/ply/blob/b88ccfe9c111739d77d9c8400b2425f1130753ed/ply-core/src/Ply/Core/Types.hs#L40).

**Comment by SeungheonOh** [comment]
Also, I found out that `ply` only supports writing from `Plutarch` terms. It's impossible to import unapplied `Script` into `ply`.

**Comment by SeungheonOh** [comment]
New thought:

We can use `TypedScriptEnvelope` from `ply` as the intermediate representation. We can export that into JSON very easily, we can use it for testing, we can use it in other projects easily as well.

That means `plutarch-export-script` won't really need a general type interface. It will remain as the script server.

**Comment by peter-mlabs** [comment]
moved to notion:
https://www.notion.so/liqwid/Make-more-general-interface-2c68b55438ba4097a972de357618302e
